- frappe/core/doctype/file/file.py
- frappe/utils/global_search.py
FYI : I did not make the cherry-pick to make sure since we are way behind frappe repo.
https://github.com/newmatik/Newmatik/issues/1659
Based on frappe commit: https://github.com/frappe/frappe/commit/6c7be62f241bc5f2280527581efd3dabefb548a8
> fix(upload):Upload datasheet URL

- frappe/api.py
Show 401 http code for expired token.
> fix(Token Expire) Give 401 http code

- frappe/templates/includes/login/login.js
re: https://github.com/newmatik/Newmatik/issues/1989
> refactor(login):If Logged in Redirect to Desk

- frappe/public/js/frappe/form/print.js
re: https://github.com/newmatik/newmatik/issues/2158
> fix(print-preview): Default language set fix

- frappe/api.py
re: https://github.com/newmatik/newmatik/issues/2312
> fix(py3): Indentation fixes

- frappe/public/js/frappe/file_uploader/FileUploader.vue
- frappe/public/js/frappe/file_uploader/index.js
https://github.com/newmatik/newmatik/issues/1356
> feat(FileUploader): Disable uploads on public access

- frappe/public/js/frappe/desk.js
I wanted to do it the simplest way possible because it will in newmatik/frappe core repo and involves session and user. I just needed little digging and time, I was able to do it. 
re: https://github.com/newmatik/newmatik/issues/2391
> feat(Desk): Redirect user based on Module Acces

- frappe/public/js/frappe/desk.js
re: https://github.com/newmatik/newmatik/issues/2412
> fix(Desk): Force redirect only for desk

- frappe/public/js/frappe/form/footer/timeline.js
re https://github.com/newmatik/newmatik/issues/2122
> feat(timeline.js): only able to delete own comments

- frappe/api.py
re: https://github.com/newmatik/newmatik/issues/2829
> fix(tab-inconsistenty): Py3 issue

- frappe/public/js/frappe/form/controls/text_editor.js
- package.json
- yarn.lock
re https://github.com/newmatik/newmatik/issues/3199
change will apply to all text editor field.
> feat(controls/text_editor): resize image on content editor

- frappe/integrations/doctype/dropbox_settings/dropbox_settings.py
re: https://github.com/newmatik/newmatik/issues/3297#issuecomment-665379429
> fix(Dropbox): No timeout

- frappe/integrations/doctype/letmeship/letmeship.py
This PR is related to https://github.com/newmatik/erpnext/pull/87
Slight refactor on letmeship api. Added a function to set letmeship specific fields on contact.
> refactor(letmeship): create function to set specific fields

- frappe/desk/form/utils.py
- frappe/utils/file_manager.py
re: https://github.com/newmatik/newmatik/issues/3438
Andrea raised an issue that notification email is not being sent. Upon investigating I realized the whole @mention is not working from the past couple of days.
Reverted the Broken Image fix because that is causing the mention to fail.
Fixed the Broken image issue in a different manner.
Sent a PR to core as well.
https://github.com/frappe/frappe/pull/11337
> fix(Comment):  Mention fix and Image fix

- frappe/core/doctype/user/user.py
- frappe/public/js/frappe/form/sidebar/assign_to.js
re https://github.com/newmatik/newmatik/issues/3441
re https://github.com/newmatik/newmatik/pull/3456
> feat(Assign To): route to new newmatik endpoint with assign to

- frappe/utils/redis_wrapper.py
re: https://github.com/newmatik/newmatik/issues/3537
> fix(API Call): Error fix

- frappe/core/doctype/user/user.py
- frappe/desk/form/utils.py
- frappe/public/js/frappe/form/sidebar/assign_to.js
- frappe/utils/file_manager.py
https://github.com/newmatik/newmatik/issues/3547
https://github.com/newmatik/newmatik/issues/3548
> Mention fix and Assign to Route

- frappe/core/doctype/comment/comment.py
re: https://github.com/elexess/eso-newmatik/issues/4188#issuecomment-828090219
**Email gets sent to only Carly and Dominik and not Ludmilla**
> refactor(Mention): Do not send email to esonetz

- frappe/public/js/frappe/desk.js
- frappe/public/js/frappe/form/controls/base_input.js
- frappe/public/js/frappe/form/controls/data.js
- frappe/public/js/frappe/form/controls/date.js
- frappe/public/js/frappe/form/controls/link.js
- frappe/public/js/frappe/form/form.js
re https://github.com/elexess/eso-newmatik/issues/4254
Old behavior:
Fixed:
`cherry-pick`ed commits for the fix to issue frappe#12323.
> fix(core): Fix having to press "Save" button twice after editing field

- frappe/core/doctype/file/file.py
[ISSUE](https://github.com/elexess/eso-newmatik/issues/5277)
> fix(file.py):Image in Comments saved under its Reference Doctype

- frappe/api.py
[Issue](https://github.com/elexess/eso-newmatik/issues/3867)
Added some changes on api.py cos I couldn't log in successfully from next to V13 eso
proof that I was able to login
> fix(api.py): change auth and oauth for next login

- frappe/desk/query_report.py
Issue: Index out of range when trying to generate a report in Missing Parts List
I have also checked this in our production and the same thing is happening.
Solution:
Implement our query_report changes from v12 to v13
Before:
After:
> fix(query_report.js): Fix Index out of range normalize function

- frappe/public/js/frappe/views/communication.js
Asana Issue: https://app.asana.com/0/1202487840949165/1202675178244113/f
Problem: Email Template Not Found after clicking on Email Button
Screenshot:
Solution: Add a validation if there's no email template, then return nothing
Screenshot
> Fix(Communication.js): Email Not Found

- frappe/email/doctype/auto_email_report/auto_email_report.py
Asana: https://app.asana.com/0/1202488272591408/1202929499746639
The reason why the report is not sending because there are changes in querry_report.py which we change it to our v12 code, but we missed updating the other functions that uses the code inside querry_report.py. With that, I updated the auto_email_report.py specifically the get_report_content function to our v12 code.
> fix(auto_email_report.py): change the code for get_report_content 

- frappe/public/js/frappe/form/form.js
re : https://app.asana.com/0/1202488269220482/1202776263653665
Create function for color indicators used for data field types.
> feat(form.js)Indicator for data fieldtypes

- frappe/public/js/frappe/form/form.js
https://github.com/elexess/eso-frappe/pull/70
> Fix(form.js):Undeclared value

- frappe/public/js/frappe/form/footer/base_timeline.js
> refactor(HSC): Hide HSC Button

- frappe/model/rename_doc.py
ref : No asana task
Issue: Renaming tool does not accept other arguments. e.g (merge, force, etc.)
Fix:
> fix(rename_doc.py) Allow other arugments for renaming tool

- frappe/auth.py
Additional Login Validation to Restrict Non-Employees from Logging in to ERP
-----
Kindly refer to the attached vids below as reference:
https://user-images.githubusercontent.com/58759735/223616262-797a45c5-3b2c-4c51-b1e8-b4001742b61b.mp4
> Feat(auth.py): authentication for non employees
